#!/usr/bin/env bash

function runDocker
{
    local -r dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
    local -r projectRoot=$(readlink -f "${dir}/../../")

    local -r applicationTagName=$(cat ${dir}/tagName);

    docker run --rm -v $(pwd):/home/app/src ${applicationTagName} "$@"
}

runDocker "$@"
